In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Finaloutput.csv", low_memory=False)

In [3]:
df.head()

Unnamed: 0  loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  \
0           0       5000         5000           4975.0    36     10.65   
1           1       2500         2500           2500.0    60     15.27   
2           2       2400         2400           2400.0    36     15.96   
3           3      10000        10000          10000.0    36     13.49   
4           4       3000         3000           3000.0    60     12.69   

   installment  emp_length  annual_inc  loan_status  ...  C4  C5  D1  D2  D3  \
0       162.87        10.0     24000.0   Fully Paid  ...   0   0   0   0   0   
1        59.83         0.5     30000.0  Charged Off  ...   1   0   0   0   0   
2        84.33        10.0     12252.0   Fully Paid  ...   0   1   0   0   0   
3       339.31        10.0     49200.0   Fully Paid  ...   0   0   0   0   0   
4        67.79         1.0     80000.0      Current  ...   0   0   0   0   0   

   D4  D5  E  F  G  
0   0   0  0  0  0  
1   0   0  0  0  0  
2   0   0  0  0  0  
3   0   0  0  0  0  
4   0   0  0  0  0  

[5 rows x 87 columns]

In [4]:
df.shape

(466285, 87)

In [4]:
dftemp = df.iloc[:,-39:]

In [5]:
df.drop(columns=df.columns[-39:], 
        axis=1, 
        inplace=True)

In [6]:
df.shape

(466285, 48)

In [8]:
df.head()

Unnamed: 0  loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  \
0           0       5000         5000           4975.0    36     10.65   
1           1       2500         2500           2500.0    60     15.27   
2           2       2400         2400           2400.0    36     15.96   
3           3      10000        10000          10000.0    36     13.49   
4           4       3000         3000           3000.0    60     12.69   

   installment  emp_length  annual_inc  loan_status  ...  RENT  \
0       162.87        10.0     24000.0   Fully Paid  ...     1   
1        59.83         0.5     30000.0  Charged Off  ...     1   
2        84.33        10.0     12252.0   Fully Paid  ...     1   
3       339.31        10.0     49200.0   Fully Paid  ...     1   
4        67.79         1.0     80000.0      Current  ...     1   

   Source Verified  Verified  y  credit_card  debt_consolidation  \
0                0         1  0            1                   0   
1                1         0  0            0                   0   
2                0         0  0            0                   0   
3                1         0  0            0                   0   
4                1         0  0            0                   0   

   home_improvement  major_purchase  other  small_business  
0                 0               0      0               0  
1                 0               0      0               0  
2                 0               0      0               1  
3                 0               0      1               0  
4                 0               0      1               0  

[5 rows x 48 columns]

In [8]:
pd.set_option('display.max_columns', None)
df.head()

Unnamed: 0  loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  \
0           0       5000         5000           4975.0    36     10.65   
1           1       2500         2500           2500.0    60     15.27   
2           2       2400         2400           2400.0    36     15.96   
3           3      10000        10000          10000.0    36     13.49   
4           4       3000         3000           3000.0    60     12.69   

   installment  emp_length  annual_inc  loan_status    dti  delinq_2yrs  \
0       162.87        10.0     24000.0   Fully Paid  27.65          0.0   
1        59.83         0.5     30000.0  Charged Off   1.00          0.0   
2        84.33        10.0     12252.0   Fully Paid   8.72          0.0   
3       339.31        10.0     49200.0   Fully Paid  20.00          0.0   
4        67.79         1.0     80000.0      Current  17.94          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  revol_util  total_acc  \
0             1.0       3.0      0.0      13648        83.7        9.0   
1             5.0       3.0      0.0       1687         9.4        4.0   
2             2.0       2.0      0.0       2956        98.5       10.0   
3             1.0      10.0      0.0       5598        21.0       37.0   
4             0.0      15.0      0.0      27783        53.9       38.0   

   out_prncp  out_prncp_inv   total_pymnt  total_pymnt_inv  total_rec_prncp  \
0        0.0            0.0   5861.071414          5831.78          5000.00   
1        0.0            0.0   1008.710000          1008.71           456.46   
2        0.0            0.0   3003.653644          3003.65          2400.00   
3        0.0            0.0  12226.302210         12226.30         10000.00   
4      766.9          766.9   3242.170000          3242.17          2233.10   

   total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  \
0         861.07                0.00        0.00                     0.00   
1         435.17                0.00      117.08                     1.11   
2         603.65                0.00        0.00                     0.00   
3        2209.33               16.97        0.00                     0.00   
4        1009.07                0.00        0.00                     0.00   

   last_pymnt_amnt  collections_12_mths_ex_med  policy_code  acc_now_delinq  \
0           171.62                         0.0            1             0.0   
1           119.66                         0.0            1             0.0   
2           649.91                         0.0            1             0.0   
3           357.48                         0.0            1             0.0   
4            67.79                         0.0            1             0.0   

   tot_coll_amt  tot_cur_bal  total_rev_hi_lim  MORTGAGE  NONE  OTHER  OWN  \
0           0.0      81539.0           22800.0         0     0      0    0   
1           0.0      81539.0           22800.0         0     0      0    0   
2           0.0      81539.0           22800.0         0     0      0    0   
3           0.0      81539.0           22800.0         0     0      0    0   
4           0.0      81539.0           22800.0         0     0      0    0   

   RENT  Source Verified  Verified  y  credit_card  debt_consolidation  \
0     1                0         1  0            1                   0   
1     1                1         0  0            0                   0   
2     1                0         0  0            0                   0   
3     1                1         0  0            0                   0   
4     1                1         0  0            0                   0   

   home_improvement  major_purchase  other  small_business  
0                 0               0      0               0  
1                 0               0      0               0  
2                 0               0      0               1  
3                 0               0      1               0  
4                 0           

In [9]:
df.drop('Unnamed: 0',axis=1,inplace=True )

In [10]:
df.head()

loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  installment  \
0       5000         5000           4975.0    36     10.65       162.87   
1       2500         2500           2500.0    60     15.27        59.83   
2       2400         2400           2400.0    36     15.96        84.33   
3      10000        10000          10000.0    36     13.49       339.31   
4       3000         3000           3000.0    60     12.69        67.79   

   emp_length  annual_inc  loan_status    dti  delinq_2yrs  inq_last_6mths  \
0        10.0     24000.0   Fully Paid  27.65          0.0             1.0   
1         0.5     30000.0  Charged Off   1.00          0.0             5.0   
2        10.0     12252.0   Fully Paid   8.72          0.0             2.0   
3        10.0     49200.0   Fully Paid  20.00          0.0             1.0   
4         1.0     80000.0      Current  17.94          0.0             0.0   

   open_acc  pub_rec  revol_bal  revol_util  total_acc  out_prncp  \
0       3.0      0.0      13648        83.7        9.0        0.0   
1       3.0      0.0       1687         9.4        4.0        0.0   
2       2.0      0.0       2956        98.5       10.0        0.0   
3      10.0      0.0       5598        21.0       37.0        0.0   
4      15.0      0.0      27783        53.9       38.0      766.9   

   out_prncp_inv   total_pymnt  total_pymnt_inv  total_rec_prncp  \
0            0.0   5861.071414          5831.78          5000.00   
1            0.0   1008.710000          1008.71           456.46   
2            0.0   3003.653644          3003.65          2400.00   
3            0.0  12226.302210         12226.30         10000.00   
4          766.9   3242.170000          3242.17          2233.10   

   total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  \
0         861.07                0.00        0.00                     0.00   
1         435.17                0.00      117.08                     1.11   
2         603.65                0.00        0.00                     0.00   
3        2209.33               16.97        0.00                     0.00   
4        1009.07                0.00        0.00                     0.00   

   last_pymnt_amnt  collections_12_mths_ex_med  policy_code  acc_now_delinq  \
0           171.62                         0.0            1             0.0   
1           119.66                         0.0            1             0.0   
2           649.91                         0.0            1             0.0   
3           357.48                         0.0            1             0.0   
4            67.79                         0.0            1             0.0   

   tot_coll_amt  tot_cur_bal  total_rev_hi_lim  MORTGAGE  NONE  OTHER  OWN  \
0           0.0      81539.0           22800.0         0     0      0    0   
1           0.0      81539.0           22800.0         0     0      0    0   
2           0.0      81539.0           22800.0         0     0      0    0   
3           0.0      81539.0           22800.0         0     0      0    0   
4           0.0      81539.0           22800.0         0     0      0    0   

   RENT  Source Verified  Verified  y  credit_card  debt_consolidation  \
0     1                0         1  0            1                   0   
1     1                1         0  0            0                   0   
2     1                0         0  0            0                   0   
3     1                1         0  0            0                   0   
4     1                1         0  0            0                   0   

   home_improvement  major_purchase  other  small_business  
0                 0               0      0               0  
1                 0               0      0               0  
2                 0               0      0               1  
3                 0               0      1               0  
4                 0               0      1               0

In [11]:
df.shape

(466285, 47)

In [12]:
y= df['loan_status']

In [13]:
x= df.drop("loan_status", axis=1)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
     x, y, test_size=0.35, random_state=42)

In [15]:
## feature Scaling 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [16]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [18]:
classifier = svm.SVC(kernel='linear')

In [19]:
df.shape

(466285, 47)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
algorithm = LogisticRegression(penalty='l2', dual=False, tol=1e-4,
C=1.0, fit_intercept=True, max_iter=1200)

In [19]:
Logistic_Regression_Model = algorithm.fit(X_train, y_train)

In [20]:
predictions = Logistic_Regression_Model.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix = confusion_matrix(y_test,predictions )
print(confusion_matrix)
print(accuracy_score(y_test,predictions))

[[14683     0     0    31     3   281     0     0     0]
 [    0 77850     0     3     5   347     5     1    73]
 [    0   275     0     0     0     0     0     0     6]
 [  137     0     0   127     4     6     0     0     0]
 [    1     0     0     1   256   430     0     0     1]
 [   29     0     0     2   115 64509     0     0     0]
 [    0  1104     0     0     0    13     1     0    21]
 [    0   403     0     0     0     3     0     0     4]
 [    0  2384     0     0     0    16     3     0    67]]
0.965030637254902


In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [32]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [33]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [34]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[14700     0     0    30     2   265     0     1     0]
 [    1 77668     0     2     5   509     7     0    92]
 [    0   275     0     0     0     0     0     0     6]
 [  130     0     0   131     6     7     0     0     0]
 [    2     0     0     6   241   440     0     0     0]
 [   27     0     0     8   109 64511     0     0     0]
 [    0  1093     0     0     1    16     0     0    29]
 [    0   399     0     0     0     4     0     0     7]
 [    0  2372     0     0     0    19     2     0    77]]
0.9640196078431372


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                     precision    recall  f1-score   support

                                        Charged Off       0.99      0.98      0.98     14998
                                            Current       0.95      0.99      0.97     78284
                                            Default       0.00      0.00      0.00       281
Does not meet the credit policy. Status:Charged Off       0.74      0.48      0.58       274
 Does not meet the credit policy. Status:Fully Paid       0.66      0.35      0.46       689
                                         Fully Paid       0.98      1.00      0.99     64655
                                    In Grace Period       0.00      0.00      0.00      1139
                                  Late (16-30 days)       0.00      0.00      0.00       410
                                 Late (31-120 days)       0.36      0.03      0.06      2470

                                           accuracy                 

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
from imblearn.over_sampling import RandomOverSampler